### ISSUE TITLE
有计划支持 公式的转换吗

### ISSUE THREAD

**Issue by UchihaArk** [ArtifexSoftware/pdf2docx#263]
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37822176/9bbb1b57-5ac0-429c-b816-9246775c0297)

**Comment by parksmallfish** [comment]
+1

**Comment by nunamia** [comment]
nougat

**Comment by JorjMcKie** [comment]
No, we will never support this.
The reason is that there is no way to **_extract_** formulas from a PDF page. Which of course would be the first prerequisite for any intention like this.
Formulas can be anything: an image, vector graphics, text or any combination of all these things.

If a formula is given completely as an image or a vector graphic, then they will appear as an image on the resulting DOCX automatically. So this case is already covered.

Other formats are not detectable as a _formula_ but mostly appear as text intermingled with some vector graphics.

So we can forget about this idea.
